T: 50
arch_name: DiT
batch_size: 512
control_freq: 30
env_config: output/smp_prior_g1_lafan/env_config.yaml
estimate_mode: epsilon
grad_clip_norm: 1.0
loss_type: l1
lr: 0.0001
model_ema: true
model_ema_decay: 0.995
model_ema_steps: 10
model_ema_update_after: 5000
model_name: tiny_mdm
motion_file: data/datasets/dataset_g1_lafan.yaml
noise_schedule_mode: squaredcos_cap_v2
normalizer_std_clip: 0.2
num_attention_heads: 4
num_iterations: 500000
num_layers: 2
num_samples_stat: 10000
output_iter: 2000
